### ISSUE TITLE
[Low Prio] Invalid JSON-LD syntax; a term definition must not contain type

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#180]
Connection to Lemmy, tested with my own instance at [fapsi.be](https://fapsi.be). Even group avatar will not get fetched. 

```
Traceback (most recent call last):
  File "/root/docker/takahe/stator/models.py", line 171, in atransition_attempt
    next_state = await current_state.handler(self)
  File "/root/docker/takahe/users/models/inbox_message.py", line 25, in handle_received
    await sync_to_async(PostInteraction.handle_ap)(instance.message)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/dist-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 284, in handle_ap
    interaction = cls.by_ap(data, create=True)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 256, in by_ap
    post = Post.by_object_uri(data["object"], fetch=True)
  File "/root/docker/takahe/activities/models/post.py", line 737, in by_object_uri
    canonicalise(response.json(), include_security=True),
  File "/root/docker/takahe/core/ld.py", line 426, in canonicalise
    return jsonld.compact(jsonld.expand(json_data), context)
  File "/usr/local/lib/python3.10/dist-packages/pyld/jsonld.py", line 163, in expand
    return JsonLdProcessor().expand(input_, options)
  File "/usr/local/lib/python3.10/dist-packages/pyld/jsonld.py", line 870, in expand
    expanded = self._expand(active_ctx, None, document, options,
  File "/usr/local/lib/python3.10/dist-packages/pyld/jsonld.py", line 2302, in _expand
    active_ctx = self._process_context(
  File "/usr/local/lib/python3.10/dist-packages/pyld/jsonld.py", line 3288, in _process_context
    self._create_term_definition(rval, ctx, k, defined, options,
  File "/usr/local/lib/python3.10/dist-packages/pyld/jsonld.py", line 5092, in _create_term_definition
    raise JsonLdError(
pyld.jsonld.JsonLdError: ('Invalid JSON-LD syntax; a term definition must not contain type',)
Type: jsonld.SyntaxError
Code: invalid term definition
Details: {'context': {'stickied': 'as:stickied', 'pt': 'https://join-lemmy.org#', 'sc': 'http://schema.org#', 'matrixUserId': {'type': 'sc:Text', 'id': 'as:alsoKnownAs'}, 'sensitive': 'as:sensitive', 'comments_enabled': {'type': 'sc:Boolean', 'id': 'pt:commentsEnabled'}, 'moderators': 'as:moderators'}}
Traceback (most recent call last):
  File "/root/docker/takahe/activities/models/post_interaction.py", line 250, in by_ap
    boost = cls.objects.get(object_uri=data["id"])
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
activities.models.post_interaction.PostInteraction.DoesNotExist: PostInteraction matching query does not exist.
```

**Comment by andrewgodwin** [comment]
Oh dear. If it's invalid JSON-LD from the other end I'm not sure what to do - I'll have to go run a fetch manually and look through the document they send over.

**Comment by TkTech** [comment]
See #202 for the ld-json.

**Comment by andrewgodwin** [comment]
We figured out this was a bug in Lemmy that they've fixed.
