### ISSUE TITLE
ValueError: time data '2022-12-16T13:32:08+00:00' does not match format

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#187]
I wonder about this, because `2022-12-16T13:32:08+00:00` is normally valid. I think the `Z` in `%Y-%m-%dT%H:%M:%S.%fZ` is "dematching" the date? Please correct me, if I'm wrong.

```
Traceback (most recent call last):
  File "/root/docker/takahe/core/ld.py", line 449, in parse_ld_date
    return datetime.datetime.strptime(value, DATETIME_FORMAT).replace(
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-12-16T13:32:08+00:00' does not match format '%Y-%m-%dT%H:%M:%SZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/docker/takahe/stator/models.py", line 171, in atransition_attempt
    next_state = await current_state.handler(self)
  File "/root/docker/takahe/users/models/inbox_message.py", line 25, in handle_received
    await sync_to_async(PostInteraction.handle_ap)(instance.message)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/dist-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 284, in handle_ap
    interaction = cls.by_ap(data, create=True)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 256, in by_ap
    post = Post.by_object_uri(data["object"], fetch=True)
  File "/root/docker/takahe/activities/models/post.py", line 741, in by_object_uri
    post = cls.by_ap(
  File "/root/docker/takahe/activities/models/post.py", line 671, in by_ap
    post.published = parse_ld_date(data.get("published"))
  File "/root/docker/takahe/core/ld.py", line 453, in parse_ld_date
    return datetime.datetime.strptime(value, DATETIME_MS_FORMAT).replace(
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-12-16T13:32:08+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

**Comment by andrewgodwin** [comment]
It means the timezone is not in UTC (Z is for "zulu" or "zero", which is what it's sometimes referred to as).

What object is this happening on? Can you paste an example?

**Comment by kromonos** [comment]
I've seen this in stators error log. Can't say, what triggered it.  
But isn't 2022-12-16T13:32:08**+00:00** same as UTC?

**Comment by andrewgodwin** [comment]
It is, but our parser is just not clever enough to see that. I'll add it in later today.

(I might bet this is not a Mastodon message it's trying to parse but a different server, too)
