### ISSUE TITLE
[Stator] 'dict' object has no attribute 'decode'

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#189]
Got from stator:

```
Traceback (most recent call last):
  File "/root/docker/takahe/stator/models.py", line 171, in atransition_attempt
    next_state = await current_state.handler(self)
  File "/root/docker/takahe/users/models/inbox_message.py", line 25, in handle_received
    await sync_to_async(PostInteraction.handle_ap)(instance.message)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/dist-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 284, in handle_ap
    interaction = cls.by_ap(data, create=True)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 256, in by_ap
    post = Post.by_object_uri(data["object"], fetch=True)
  File "/root/docker/takahe/activities/models/post.py", line 728, in by_object_uri
    response = async_to_sync(SystemActor().signed_request)(
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 218, in __call__
    return call_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 282, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/root/docker/takahe/users/models/system_actor.py", line 69, in signed_request
    return await HttpSignature.signed_request(
  File "/root/docker/takahe/core/signatures.py", line 185, in signed_request
    uri_parts = urlparse(uri)
  File "/usr/lib/python3.10/urllib/parse.py", line 391, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib/python3.10/urllib/parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib/python3.10/urllib/parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib/python3.10/urllib/parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'dict' object has no attribute 'decode'
```

**Comment by andrewgodwin** [comment]
Unless I can also get the object behind this, I can't do much with this traceback (also I think I fixed something very similar earlier today)

**Comment by kromonos** [comment]
OK. I'll try to watch and try to pick more information, when I see it again.

**Comment by andrewgodwin** [comment]
In general, random Stator errors are not too important to report unless functionality breaks, it's designed to error and retry. We have Stator on takahe.social wired directly into Sentry, so I use that to go around and fix the noisy errors in batches.

**Comment by kromonos** [comment]
Oh, damn. I knew I forgot something.

**Comment by andrewgodwin** [comment]
Going to close this as it's a general error that comes from a lot of things (several of which have been fixed), and we have monitoring for it on the takahe.social sentry.
