### ISSUE TITLE
[Stator]  'NoneType' object has no attribute 'local'

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#190]
```
Traceback (most recent call last):
  File "/root/docker/takahe/stator/models.py", line 171, in atransition_attempt
    next_state = await current_state.handler(self)
  File "/root/docker/takahe/users/models/inbox_message.py", line 25, in handle_received
    await sync_to_async(PostInteraction.handle_ap)(instance.message)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/dist-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 284, in handle_ap
    interaction = cls.by_ap(data, create=True)
  File "/root/docker/takahe/activities/models/post_interaction.py", line 256, in by_ap
    post = Post.by_object_uri(data["object"], fetch=True)
  File "/root/docker/takahe/activities/models/post.py", line 742, in by_object_uri
    post = cls.by_ap(
  File "/root/docker/takahe/activities/models/post.py", line 684, in by_ap
    emoji = Emoji.by_ap_tag(post.author.domain, tag, create=True)
  File "/root/docker/takahe/activities/models/emoji.py", line 245, in by_ap_tag
    domain=None if domain.local else domain,
AttributeError: 'NoneType' object has no attribute 'local'
```

**Comment by andrewgodwin** [comment]
My guess on this one is that an emoji came in from an author that had never been seen before and wasn't fetched yet. Stator will retry and fix this itself most likely, we just need slightly less noisy error handling.
