### ISSUE TITLE
Maybe Pleroma only emojireact

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#304]
Could also be from MissKey:  
```
users-runner     | Tasks processed this loop:
users-runner     |   users.inboxmessage: 2
users-runner     | Running cleaning and scheduling
users-runner     | Attempting transition on users.inboxmessage#69809 from state received
users-runner     | Traceback (most recent call last):
users-runner     |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 486, in thread_handler
users-runner     |     raise exc_info[1]
users-runner     |   File "/takahe/stator/models.py", line 172, in atransition_attempt
users-runner     |     next_state = await current_state.handler(self)  # type: ignore
users-runner     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
users-runner     |   File "/takahe/users/models/inbox_message.py", line 120, in handle_received
users-runner     |     raise ValueError(f"Cannot handle activity of type {unknown}")
users-runner     | ValueError: Cannot handle activity of type http://litepub.social/ns#emojireact
```

Personally, I'm feeling a bit mixed about the function. Surely it is sometimes quite nice, but necessary? Not really. After all, there is the little star under the message. Admittedly, the emoji reaction could express other “feelings” as well, than just like.

**Comment by andrewgodwin** [comment]
Oh right, emoji reactions. I'll just put in a thing to drop and ignore these for now and we'll revisit if we want to support them in future.

**Comment by whatSocks** [comment]
Another option is to treat them like favorites, which is how I believe mastodon handles emojireacts from fedibird

**Comment by andrewgodwin** [comment]
I hesitated to do that given that the emoji in the react might be negative, but if it's an established pattern...

**Comment by kromonos** [comment]
I think, a reaction is a reaction, never mind, if it's a star, or an emoji. If it's meant negative, that's ok. That's on their side, but it hasn't meant to be negative on Takahe side?

**Comment by shuuji3** [comment]
It looks like both Misskey and Firefish are sending the `type=Like` object at this time. So Takahē already accepts any emoji reaction on the other server as a like reaction now.

Here's an example object sent from Firefish when I send `😇` reaction:

```python
{
    'id': 'https://firefish.social/likes/9ik9ujpnd11k67xc',
    'type': 'Like',
    'actor': 'https://firefish.social/users/9i761tefz4uyltlz',
    'object': 'https://takahe.shuuji3.xyz/@shuuji3@takahe.shuuji3.xyz/posts/215037658374555952/',
    'content': '😇',
    '@context': [
        'https://www.w3.org/ns/activitystreams',
        'https://w3id.org/security/v1',
        {
            'toot': 'http://joinmastodon.org/ns#',
            'Emoji': 'toot:Emoji',
            'isCat': 'misskey:isCat',
            'value': 'schema:value',
            'vcard': 'http://www.w3.org/2006/vcard/ns#',
            'schema': 'http://schema.org#',
            'Hashtag': 'as:Hashtag',
            'misskey': 'https://misskey-hub.net/ns#',
            'featured': 'toot:featured',
            'fedibird': 'http://fedibird.com/ns#',
            'quoteUri': 'fedibird:quoteUri',
            'quoteUrl': 'as:quoteUrl',
            'sensitive': 'as:sensitive',
            'movedToUri': 'as:movedTo',
            'discoverable': 'toot:discoverable',
            'PropertyValue': 'schema:PropertyValue',
            '_misskey_talk': 'misskey:_misskey_talk',
            '_misskey_quote': 'misskey:_misskey_quote',
            '_misskey_votes': 'misskey:_misskey_votes',
            '_misskey_content':'misskey:_misskey_content',
            '_misskey_reaction': 'misskey:_misskey_reaction',
            'manuallyApprovesFollowers': 'as:manuallyApprovesFollowers'
        },
        'https://w3id.org/security/v1'
    ],
    '_misskey_reaction': '😇'
}
```

**On Firefish**
<img width="656" alt="Screenshot 2023-08-19 at 0 34 47" src="https://github.com/jointakahe/takahe/assets/1425259/459711a9-ddbe-40cb-8682-630e58051f8c">

**Takahē on Elk**
<img width="701" alt="Screenshot 2023-08-18 at 23 26 57" src="https://github.com/jointakahe/takahe/assets/1425259/fe472974-5c85-409f-b48c-b76fd454847f">

So this issue had already been resolved without any action...?

I agree it's a bit weird to be liked even if it's `👎🏻` reaction. But both UI shows the server icon on a user account if they use a different application with an icon, so at least users can be aware when sending a reaction to Takahē account.

**Comment by andrewgodwin** [comment]
This ticket was more "actually support emoji reactions" in my mind rather than merely translating them all to Likes (which is what Mastodon does anyway, so :-1: being a star is kind of expected behaviour for most servers!)

**Comment by AstraLuma** [comment]
Ok, I'm guessing three bits here:

* Make sure reactions are correctly accepted and stored
* Make sure reactions are correctly aggregated and forwarded
* Update the UI to display reactions

**Comment by andrewgodwin** [comment]
Yeah - PostInteraction is prepped to accept arbitrary reaction types, so the problem is mostly inbound and outbound comms.

The mastadon API has no way of seeing these reactions or sending them though, so I don't know how important it is (they'll only be visible on the web UI from external sources)

**Comment by AstraLuma** [comment]
Do we have any example activities of unreacting?

**Comment by AstraLuma** [comment]
The firefish UI suggests it only supports one reaction per user.

**Comment by AstraLuma** [comment]
Ok, some example messages:

```
{
  "id": "https://fediverse.gay/likes/9lv0n6wjz85mpu6p",
  "type": "Like",
  "actor": "https://fediverse.gay/users/9ltneg7gvuorfb2i",
  "object": "https://derez.zone/@astraluma@derez.zone/posts/244939510870121776/",
  "content": "❤️",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "toot": "http://joinmastodon.org/ns#",
      "Emoji": "toot:Emoji",
      "isCat": "misskey:isCat",
      "value": "schema:value",
      "vcard": "http://www.w3.org/2006/vcard/ns#",
      "schema": "http://schema.org#",
      "Hashtag": "as:Hashtag",
      "misskey": "https://misskey-hub.net/ns#",
      "featured": "toot:featured",
      "fedibird": "http://fedibird.com/ns#",
      "quoteUri": "fedibird:quoteUri",
      "quoteUrl": "as:quoteUrl",
      "sensitive": "as:sensitive",
      "movedToUri": "as:movedTo",
      "discoverable": "toot:discoverable",
      "PropertyValue": "schema:PropertyValue",
      "_misskey_talk": "misskey:_misskey_talk",
      "_misskey_quote": "misskey:_misskey_quote",
      "_misskey_votes": "misskey:_misskey_votes",
      "_misskey_content": "misskey:_misskey_content",
      "_misskey_reaction": "misskey:_misskey_reaction",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
    },
    "https://w3id.org/security/v1"
  ],
  "_misskey_reaction": "❤️"
}
```

```
{
  "id": "https://fediverse.gay/likes/9lv0n6wjz85mpu6p/undo",
  "type": "Undo",
  "actor": "https://fediverse.gay/users/9ltneg7gvuorfb2i",
  "object": {
    "id": "https://fediverse.gay/likes/9lv0n6wjz85mpu6p",
    "type": "Like",
    "actor": "https://fediverse.gay/users/9ltneg7gvuorfb2i",
    "object": "https://derez.zone/@astraluma@derez.zone/posts/244939510870121776/",
    "content": "❤️",
    "_misskey_reaction": "❤️"
  },
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "toot": "http://joinmastodon.org/ns#",
      "Emoji": "toot:Emoji",
      "isCat": "misskey:isCat",
      "value": "schema:value",
      "vcard": "http://www.w3.org/2006/vcard/ns#",
      "schema": "http://schema.org#",
      "Hashtag": "as:Hashtag",
      "misskey": "https://misskey-hub.net/ns#",
      "featured": "toot:featured",
      "fedibird": "http://fedibird.com/ns#",
      "quoteUri": "fedibird:quoteUri",
      "quoteUrl": "as:quoteUrl",
      "sensitive": "as:sensitive",
      "movedToUri": "as:movedTo",
      "discoverable": "toot:discoverable",
      "PropertyValue": "schema:PropertyValue",
      "_misskey_talk": "misskey:_misskey_talk",
      "_misskey_quote": "misskey:_misskey_quote",
      "_misskey_votes": "misskey:_misskey_votes",
      "_misskey_content": "misskey:_misskey_content",
      "_misskey_reaction": "misskey:_misskey_reaction",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
    },
    "https://w3id.org/security/v1"
  ],
  "published": "2023-11-09T17:17:56.420Z"
}
```

I can't actually get the Iceshrimp UI to change a reaction without removing the old one, and I'm unfamiliar with the Misskey client ecosystem. (Using fediverse.gay because firefish.social is being kinda laggy in a not-confidence-inspiring way.)

**Comment by iacore** [comment]
Calling this "Emoji" Reaction might be a misnomer. The reaction content can be any text, with (misskey extension) emoji replacement.
