### ISSUE TITLE
Handle Delete of unknown objects

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#306]
Oops. What happened there?

```
inbox-runner           | Traceback (most recent call last):
inbox-runner           |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 486, in thread_handler
inbox-runner           |     raise exc_info[1]
inbox-runner           |   File "/takahe/stator/models.py", line 172, in atransition_attempt
inbox-runner           |     next_state = await current_state.handler(self)  # type: ignore
inbox-runner           |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
inbox-runner           |   File "/takahe/users/models/inbox_message.py", line 99, in handle_received
inbox-runner           |     await sync_to_async(Identity.handle_delete_ap)(instance.message)
inbox-runner           |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 448, in __call__
inbox-runner           |     ret = await asyncio.wait_for(future, timeout=None)
inbox-runner           |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
inbox-runner           |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for
inbox-runner           |     return await fut
inbox-runner           |            ^^^^^^^^^
inbox-runner           |   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 22, in run
inbox-runner           |     result = self.fn(*self.args, **self.kwargs)
inbox-runner           |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
inbox-runner           |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 490, in thread_handler
inbox-runner           |     return func(*args, **kwargs)
inbox-runner           |            ^^^^^^^^^^^^^^^^^^^^^
inbox-runner           |   File "/takahe/users/models/identity.py", line 579, in handle_delete_ap
inbox-runner           |     raise ActorMismatchError(
inbox-runner           | core.exceptions.ActorMismatchError: Actor https://social.alster.space/users/alsternerd trying to delete identity https://social.alster.space/objects/8fe6fea4-90ab-4691-9312-06f5645af976
```

**Comment by andrewgodwin** [comment]
We fire that when a message comes in that's apparently incorrect (like trying to delete something that's not yours). Any chance you can dig up the inbox message for this?

**Comment by kromonos** [comment]
He tried to delete this post: https://tavern.drow.be/@alsternerd@social.alster.space/posts/241370/  
![](https://mws.bka.li/sharex/2022/12/dbeaver_20221228_200713.png)

**Comment by andrewgodwin** [comment]
Interesting, so the thing I wonder about then is why it thinks they're trying to delete an identity. Can I see the full JSON?

**Comment by kromonos** [comment]
Should be this one:
```json
  "cc": [],
  "id": "https://social.alster.space/activities/315bfd08-da8b-4b95-8571-061c70ac3c50",
  "to": [
    "https://chaos.social/users/macsnider",
    "https://social.alster.space/users/alsternerd/followers",
    "as:Public"
  ],
  "bcc": [],
  "bto": [],
  "type": "Delete",
  "actor": "https://social.alster.space/users/alsternerd",
  "object": "https://social.alster.space/objects/8fe6fea4-90ab-4691-9312-06f5645af976",
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "toot": "http://joinmastodon.org/ns#",
      "Emoji": "toot:Emoji",
      "Public": "as:Public",
      "Hashtag": "as:Hashtag",
      "blurhash": "toot:blurhash",
      "sensitive": "as:sensitive",
      "focalPoint": {
        "@id": "toot:focalPoint",
        "@container": "@list"
      },
      "votersCount": "toot:votersCount",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers"
    },
    "https://w3id.org/security/v1"
  ]
}
```

**Comment by andrewgodwin** [comment]
Aha, yes, I see - it's a Delete without an embedded object which is why we can't handle it!
