### ISSUE TITLE
SQLite back-end not working

### ISSUE THREAD

**Issue by rcarmo** [jointakahe/takahe#325]
Apropos #68, this is what happens to the stator when I try to use `SQLite` as a back-end:

```
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/stator/models.py", line 174, in atransition_attempt
worker.1 |     next_state = await current_state.handler(self)  # type: ignore
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/hashtag.py", line 33, in handle_outdated
worker.1 |     total = await posts_query.acount()
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/query.py", line 624, in acount
worker.1 |     return await sync_to_async(self.count)()
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
worker.1 |     ret = await asyncio.wait_for(future, timeout=None)
worker.1 |   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
worker.1 |     return await fut
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
worker.1 |     result = self.fn(*self.args, **self.kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
worker.1 |     return func(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/query.py", line 621, in count
worker.1 |     return self.query.get_count(using=self.db)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/query.py", line 559, in get_count
worker.1 |     return obj.get_aggregation(using, ["__count"])["__count"]
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/query.py", line 544, in get_aggregation
worker.1 |     result = compiler.execute_sql(SINGLE)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1385, in execute_sql
worker.1 |     sql, params = self.as_sql()
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 618, in as_sql
worker.1 |     self.compile(self.where) if self.where is not None else ("", [])
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 506, in compile
worker.1 |     sql, params = node.as_sql(self, self.connection)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/where.py", line 112, in as_sql
worker.1 |     sql, params = compiler.compile(child)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 506, in compile
worker.1 |     sql, params = node.as_sql(self, self.connection)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/fields/json.py", line 148, in as_sql
worker.1 |     raise NotSupportedError(
worker.1 | django.db.utils.NotSupportedError: contains lookup is not supported on this database backend.
```

I am running stock Ubuntu 22.04 in ARM64, with `sqlite3` 3.37.2 2022-01-06 13:25:41 and Python 3.10.6, and the JSON1 extension is present in `/usr/lib/aarch64-linux-gnu/libsqlite3.so.0` (here's a `strings | grep` from it):

```
json_object() requires an even number of arguments
json_object() labels must be TEXT
json_%s() needs an odd number of arguments
json
json_group_array
json_group_object
json_each
json_tree
CREATE TABLE x(key,value,type,atom,id,parent,fullkey,path,json HIDDEN,root HIDDEN)
json_array
json_array_length
json_extract
json_insert
json_object
json_patch
json_quote
json_remove
json_replace
json_set
json_type
json_valid
```

Any chance this can be tackled without having Django build a `JSON_CONTAINS` clause?

**Comment by andrewgodwin** [comment]
Yeah this is what I was worried about with trying to support SQLite - the JSON stuff we're doing is just a little bit outside of its wheelhouse. We could work on an alternative query construction for it, but this is also why I have (for now) descoped sqlite and so I won't be officially doing any work to support it until at least 1.0. 

Patches to make this work that aren't too invasive are welcome, but I'm going to close this ticket as it is not something we will commit to doing.
