### ISSUE TITLE
Handling of interactions on missing posts

### ISSUE THREAD

**Issue by rcarmo** [jointakahe/takahe#388]
I've been getting this on my test instance for a while now (this is fresh from just now, but I can see identical errors all throughout the logs:

```
wsgi.1   | 127.0.0.1 - - [10/Jan/2023:14:11:15 +0000] "POST /inbox/ HTTP/1.1" 202 269 "-" "http.rb/5.1.0 (Mastodon/4.0.2; +https://mrnet.pt/)" 171ms
worker.1 | Attempting transition on users.inboxmessage#963 from state received
worker.1 | Attempting transition on activities.post#135641608653357184 from state new
worker.1 | Attempting transition on activities.fanout#534 from state new
worker.1 | Tasks processed this loop:
worker.1 |   users.identity: 1
worker.1 |   users.inboxmessage: 1
worker.1 |   activities.post: 1
worker.1 |   activities.fanout: 1
worker.1 | Running cleaning and scheduling
worker.1 | Attempting transition on users.inboxmessage#931 from state received
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post_interaction.py", line 262, in by_ap
worker.1 |     boost = cls.objects.get(object_uri=data["id"])
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
worker.1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
worker.1 |     raise self.model.DoesNotExist(
worker.1 | activities.models.post_interaction.PostInteraction.DoesNotExist: PostInteraction matching query does not exist.
worker.1 |
worker.1 | During handling of the above exception, another exception occurred:
worker.1 |
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 302, in main_wrap
worker.1 |     raise exc_info[1]
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post.py", line 854, in by_object_uri
worker.1 |     return cls.objects.get(object_uri=object_uri)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
worker.1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
worker.1 |     raise self.model.DoesNotExist(
worker.1 | activities.models.post.Post.DoesNotExist: Post matching query does not exist.
worker.1 |
worker.1 | During handling of the above exception, another exception occurred:
worker.1 |
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
worker.1 |     raise exc_info[1]
worker.1 |   File "/home/piku/.piku/apps/takahe/stator/models.py", line 233, in atransition_attempt
worker.1 |     next_state = await current_state.handler(self)  # type: ignore
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/inbox_message.py", line 24, in handle_received
worker.1 |     await sync_to_async(PostInteraction.handle_ap)(instance.message)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
worker.1 |     ret = await asyncio.wait_for(future, timeout=None)
worker.1 |   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
worker.1 |     return await fut
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
worker.1 |     result = self.fn(*self.args, **self.kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
worker.1 |     return func(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post_interaction.py", line 297, in handle_ap
worker.1 |     interaction = cls.by_ap(data, create=True)
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post_interaction.py", line 268, in by_ap
worker.1 |     post = Post.by_object_uri(get_str_or_id(data["object"]), fetch=True)
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post.py", line 872, in by_object_uri
worker.1 |     post = cls.by_ap(
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post.py", line 740, in by_ap
worker.1 |     if urlparse(data["id"]).hostname != urlparse(data["attributedTo"]).hostname:
worker.1 | KeyError: 'id'
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post_interaction.py", line 262, in by_ap
worker.1 |     boost = cls.objects.get(object_uri=data["id"])
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
worker.1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
worker.1 |     raise self.model.DoesNotExist(
worker.1 | activities.models.post_interaction.PostInteraction.DoesNotExist: PostInteraction matching query does not exist.
worker.1 |
worker.1 | During handling of the above exception, another exception occurred:
worker.1 |
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 302, in main_wrap
worker.1 |     raise exc_info[1]
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post.py", line 854, in by_object_uri
worker.1 |     return cls.objects.get(object_uri=object_uri)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
worker.1 |     return getattr(self.get_queryset(), name)(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
worker.1 |     raise self.model.DoesNotExist(
worker.1 | activities.models.post.Post.DoesNotExist: Post matching query does not exist.
worker.1 |
worker.1 | During handling of the above exception, another exception occurred:
worker.1 |
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/stator/models.py", line 233, in atransition_attempt
worker.1 |     next_state = await current_state.handler(self)  # type: ignore
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/inbox_message.py", line 24, in handle_received
worker.1 |     await sync_to_async(PostInteraction.handle_ap)(instance.message)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 448, in __call__
worker.1 |     ret = await asyncio.wait_for(future, timeout=None)
worker.1 |   File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
worker.1 |     return await fut
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
worker.1 |     result = self.fn(*self.args, **self.kwargs)
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 490, in thread_handler
worker.1 |     return func(*args, **kwargs)
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post_interaction.py", line 297, in handle_ap
worker.1 |     interaction = cls.by_ap(data, create=True)
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post_interaction.py", line 268, in by_ap
worker.1 |     post = Post.by_object_uri(get_str_or_id(data["object"]), fetch=True)
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post.py", line 872, in by_object_uri
worker.1 |     post = cls.by_ap(
worker.1 |   File "/home/piku/.piku/apps/takahe/activities/models/post.py", line 740, in by_ap
worker.1 |     if urlparse(data["id"]).hostname != urlparse(data["attributedTo"]).hostname:
worker.1 | KeyError: 'id'
```

**Comment by andrewgodwin** [comment]
Could you fetch that inbox message (ID 931) out of the Django admin for us and put it here?

**Comment by rcarmo** [comment]
This one is not there anymore - I cannot find anything older than 978, so it was either purged or I messed something up. But I'll add the payload if this comes up again (looking through the logs on my instance, it hasn't happened all day).

**Comment by rcarmo** [comment]
Yep. Next time I'll try to find the time to do a PR... I've little time during the week.

**Comment by andrewgodwin** [comment]
Closing this due to inactivity.
