### ISSUE TITLE
[Stator] Nodeinfo handling

### ISSUE THREAD

**Issue by rcarmo** [jointakahe/takahe#400]
A bit puzzled by this one:

```
worker.1 | Attempting transition on users.domain#federate.social from state outdated
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/domain.py", line 200, in fetch_nodeinfo
worker.1 |     info = NodeInfo(**response.json())
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/httpx/_models.py", line 752, in json
worker.1 |     return jsonlib.loads(self.text, **kwargs)
worker.1 |   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
worker.1 |     return _default_decoder.decode(s)
worker.1 |   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
worker.1 |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
worker.1 |   File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
worker.1 |     raise JSONDecodeError("Expecting value", s, err.value) from None
worker.1 | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
worker.1 |
worker.1 | During handling of the above exception, another exception occurred:
worker.1 |
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
worker.1 |     raise exc_info[1]
worker.1 |   File "/home/piku/.piku/apps/takahe/stator/models.py", line 233, in atransition_attempt
worker.1 |     next_state = await current_state.handler(self)  # type: ignore
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/domain.py", line 32, in handle_outdated
worker.1 |     info = await instance.fetch_nodeinfo()
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/domain.py", line 202, in fetch_nodeinfo
worker.1 |     raise ValueError(
worker.1 | ValueError: Client error decoding nodeinfo: domain=kottman.xyz, error=Expecting value: line 1 column 1 (char 0)
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/domain.py", line 200, in fetch_nodeinfo
worker.1 |     info = NodeInfo(**response.json())
worker.1 |   File "/home/piku/.piku/envs/takahe/lib/python3.10/site-packages/httpx/_models.py", line 752, in json
worker.1 |     return jsonlib.loads(self.text, **kwargs)
worker.1 |   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
worker.1 |     return _default_decoder.decode(s)
worker.1 |   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
worker.1 |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
worker.1 |   File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
worker.1 |     raise JSONDecodeError("Expecting value", s, err.value) from None
worker.1 | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
worker.1 |
worker.1 | During handling of the above exception, another exception occurred:
worker.1 |
worker.1 | Traceback (most recent call last):
worker.1 |   File "/home/piku/.piku/apps/takahe/stator/models.py", line 233, in atransition_attempt
worker.1 |     next_state = await current_state.handler(self)  # type: ignore
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/domain.py", line 32, in handle_outdated
worker.1 |     info = await instance.fetch_nodeinfo()
worker.1 |   File "/home/piku/.piku/apps/takahe/users/models/domain.py", line 202, in fetch_nodeinfo
worker.1 |     raise ValueError(
worker.1 | ValueError: Client error decoding nodeinfo: domain=kottman.xyz, error=Expecting value: line 1 column 1 (char 0)
wsgi.1   | 127.0.0.1 - - [12/Jan/2023:18:43:52 +0000] "POST /inbox/ HTTP/1.1" 202 269 "-" "http.rb/5.1.0 (Mastodon/4.0.2; +https://mastodon.social/)" 140ms
```

`federate.social` has this in the database:

```json
{"usage": {"users": {"total": 498, "activeMonth": 150, "activeHalfyear": 150}, "local_posts": 24030}, "version": "2.0", "metadata": {}, "software": {"name": "mastodon", "version": "4.0.2"}, "protocols": ["activitypub"], "open_registrations": true}
```

But `kottman.xyz` has a `null` value, which is consistent with a fetching error (but there's no capture of the fetched value, this might need a specific trace/logging line).

**Comment by manfre** [comment]
>  ValueError: Client error decoding nodeinfo: domain=kottman.xyz, error=Expecting value: line 1 column 1 (char 0)

kottman.xyz is returning a 200 response with an empty payload for `/.well-known/nodeinfo` and same for `/nodeinfo/2.0`. That server is either not an ActivityPub server or misconfigured.

**Comment by rcarmo** [comment]
Well, that has to be accounted for as well, I think...
