### ISSUE TITLE
Messages not sent out

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#488]
I currently have around 126 fanouts in queue, I can't send out. When I try, they return the following error message:
```
takahe-stator-1        | Traceback (most recent call last):
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 486, in thread_handler
takahe-stator-1        |     raise exc_info[1]
takahe-stator-1        |   File "/takahe/stator/models.py", line 233, in atransition_attempt
takahe-stator-1        |     next_state = await current_state.handler(self)  # type: ignore
takahe-stator-1        |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/fan_out.py", line 88, in handle_new
takahe-stator-1        |     body=canonicalise(post.to_create_ap()),
takahe-stator-1        |                       ^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/post.py", line 647, in to_create_ap
takahe-stator-1        |     object = self.to_ap()
takahe-stator-1        |              ^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/post.py", line 588, in to_ap
takahe-stator-1        |     "content": self.safe_content_remote(),
takahe-stator-1        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/post.py", line 418, in safe_content_remote
takahe-stator-1        |     return self.safe_content(local=False)
takahe-stator-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/post.py", line 405, in safe_content
takahe-stator-1        |     return func(local=local)
takahe-stator-1        |            ^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/post.py", line 377, in _safe_content_note
takahe-stator-1        |     return ContentRenderer(local=local).render_post(self.content, self)
takahe-stator-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 325, in render_post
takahe-stator-1        |     parser = FediverseHtmlParser(
takahe-stator-1        |              ^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 81, in __init__
takahe-stator-1        |     self.feed(html.replace("\n", ""))
takahe-stator-1        |   File "/usr/local/lib/python3.11/html/parser.py", line 110, in feed
takahe-stator-1        |     self.goahead(0)
takahe-stator-1        |   File "/usr/local/lib/python3.11/html/parser.py", line 172, in goahead
takahe-stator-1        |     k = self.parse_endtag(i)
takahe-stator-1        |         ^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/html/parser.py", line 413, in parse_endtag
takahe-stator-1        |     self.handle_endtag(elem)
takahe-stator-1        |   File "/takahe/core/html.py", line 119, in handle_endtag
takahe-stator-1        |     self.flush_data()
takahe-stator-1        |   File "/takahe/core/html.py", line 153, in flush_data
takahe-stator-1        |     self.html_output += self.linkify(self._data_buffer)
takahe-stator-1        |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 239, in linkify
takahe-stator-1        |     result += self.linkify_mentions(bit)
takahe-stator-1        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 260, in linkify_mentions
takahe-stator-1        |     result += self.linkify_hashtags(bit)
takahe-stator-1        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 277, in linkify_hashtags
takahe-stator-1        |     result += self.linkify_emoji(bit)
takahe-stator-1        |               ^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 297, in linkify_emoji
takahe-stator-1        |     result += self.create_emoji(bit)
takahe-stator-1        |               ^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/core/html.py", line 215, in create_emoji
takahe-stator-1        |     emoji = Emoji.get_by_domain(shortcode, self.emoji_domain)
takahe-stator-1        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/cachetools/__init__.py", line 641, in wrapper
takahe-stator-1        |     v = func(*args, **kwargs)
takahe-stator-1        |         ^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/takahe/activities/models/emoji.py", line 162, in get_by_domain
takahe-stator-1        |     return cls.objects.get(local=True, shortcode=shortcode)
takahe-stator-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
takahe-stator-1        |     return getattr(self.get_queryset(), name)(*args, **kwargs)
takahe-stator-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 646, in get
takahe-stator-1        |     num = len(clone)
takahe-stator-1        |           ^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 376, in __len__
takahe-stator-1        |     self._fetch_all()
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
takahe-stator-1        |     self._result_cache = list(self._iterable_class(self))
takahe-stator-1        |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
takahe-stator-1        |     results = compiler.execute_sql(
takahe-stator-1        |               ^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
takahe-stator-1        |     cursor = self.connection.cursor()
takahe-stator-1        |              ^^^^^^^^^^^^^^^^^^^^^^^^
takahe-stator-1        |   File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
takahe-stator-1        |     raise SynchronousOnlyOperation(message)
takahe-stator-1        | django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**Comment by andrewgodwin** [comment]
Ahh, I thought there might be something in that rewrite that the tests didn't catch. I'll get to it very soon.

**Comment by andrewgodwin** [comment]
Should be fixed by https://github.com/jointakahe/takahe/commit/4744f7d47cc151553ea7e8f6085ed6c1468caac3
