### ISSUE TITLE
[make runserver] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#489]
Error when trying **direct installation** - _make runserver_ from the doc
`https://docs.jointakahe.org/en/latest/contributing/#direct-installation`

```
docker compose -f docker/docker-compose.yml up db -d
[+] Running 1/0
 ⠿ Container docker-db-1  Running                                                                                                                                                                     0.0s
python3 -m manage runserver
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/takahe/apptest/takahe/manage.py", line 38, in <module>
    main()
  File "/home/takahe/apptest/takahe/manage.py", line 34, in main
    execute_from_command_line(sys.argv)
  File "/home/takahe/.virtualenvs/django/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/takahe/.virtualenvs/django/lib/python3.8/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/home/takahe/.virtualenvs/django/lib/python3.8/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/takahe/.virtualenvs/django/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/takahe/.virtualenvs/django/lib/python3.8/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/takahe/apptest/takahe/takahe/settings.py", line 34, in <module>
    def as_bool(v: str | list[str] | None):
TypeError: 'type' object is not subscriptable
make: *** [Makefile:54: runserver] Error 1
```

**Comment by andrewgodwin** [comment]
Your version of Python is too old - Takahē needs 3.10 at least.
