### ISSUE TITLE
Posting an image from Ivory fails

### ISSUE THREAD

**Issue by dvydra** [jointakahe/takahe#538]
I can post to my instance from Ivory without issue.
But if I include an image, Ivory fails to post. 

It seems like ivory tries to post the media, then retrieve the posted media a few times, keeps getting a 500 and eventually gives up on posting the post?

I'm on takahe sha 61830a9 and Ivory 1.2

```
[12/Mar/2023:13:32:06 +0000] "POST /api/v2/media HTTP/1.1" 200 469 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
[12/Mar/2023:13:32:09 +0000] "GET /api/v1/media/5537 HTTP/1.1" 500 3309 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
[12/Mar/2023:13:32:14 +0000] "GET /api/v1/media/5537 HTTP/1.1" 500 3309 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
[12/Mar/2023:13:32:24 +0000] "GET /api/v1/media/5537 HTTP/1.1" 500 3309 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
[12/Mar/2023:13:32:40 +0000] "GET /api/v1/media/5537 HTTP/1.1" 500 3309 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
[12/Mar/2023:13:33:00 +0000] "GET /api/v1/media/5537 HTTP/1.1" 500 3309 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
[12/Mar/2023:13:33:25 +0000] "GET /api/v1/media/5537 HTTP/1.1" 500 3309 "-" "Ivory/12001 CFNetwork/1406.0.4 Darwin/22.4.0"
```

**Comment by dvydra** [comment]
Mammoth 1.1(119) behaves very differently (and works)

```
[12/Mar/2023:13:43:31 +0000] "POST /api/v1/media HTTP/1.1" 200 469 "-" "Mammoth/119 CFNetwork/1406.0.4 Darwin/22.4.0"
```
this happens as soon as the image is attached to the draft post

```
[12/Mar/2023:13:43:40 +0000] "GET /media/attachment_thumbnails/2023/3/12/-KKG32qrZ45p8pJWS9aZuH2wwgU.webp HTTP/1.1" 200 0 "https://social.ivydra.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
[12/Mar/2023:13:43:41 +0000] "POST /api/v1/statuses HTTP/1.1" 200 2283 "-" "Mammoth/119 CFNetwork/1406.0.4 Darwin/22.4.0"
```
this happens when the post is posted.

**Comment by TkTech** [comment]
A 500 error should be generating a traceback on the server, do you have the error log?

**Comment by andrewgodwin** [comment]
I can replicate this on my own server with Ivory; traceback is 
```
Traceback (most recent call last):
  File "/home/andrew/Envs/takahe/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/andrew/Envs/takahe/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/andrew/Programs/django-hatchway/hatchway/urls.py", line 27, in __call__
    return self.callables[method](request, *args, **kwargs)
  File "/home/andrew/Programs/takahe/api/decorators.py", line 47, in inner
    return function(request, *args, **kwargs)
  File "/home/andrew/Programs/django-hatchway/hatchway/view.py", line 295, in __call__
    response = self.view(request, **kwargs)
  File "/home/andrew/Programs/takahe/api/views/media.py", line 57, in get_media
    if attachment.post.author != request.identity:
AttributeError: 'NoneType' object has no attribute 'author'
```

I'll have it fixed shortly.

**Comment by dvydra** [comment]
Confirmed fixed. Stellar work @andrewgodwin
