### ISSUE TITLE
gmail smtp fails

### ISSUE THREAD

**Issue by j2l** [jointakahe/takahe#544]
I've set a working gmail SMTP string (TAKAHE_EMAIL_SERVER: "smtp://someone%40example.com:password@smtp.gamil.com:587/") and try to create the admin user without luck:
```
Running cleaning and scheduling

No tasks handled since last flush.

Attempting transition on users.passwordreset#4 from state new

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 486, in thread_handler

    raise exc_info[1]

  File "/takahe/stator/models.py", line 234, in atransition_attempt

    next_state = await current_state.handler(self)  # type: ignore

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/takahe/users/models/password_reset.py", line 27, in handle_new

    await sync_to_async(send_mail)(

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 448, in __call__

    ret = await asyncio.wait_for(future, timeout=None)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for

    return await fut

           ^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 22, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 490, in thread_handler

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/__init__.py", line 87, in send_mail

    return mail.send()

           ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send

    return self.get_connection(fail_silently).send_messages([self])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages

    new_conn_created = self.open()

                       ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 91, in open

    self.connection.login(self.username, self.password)

  File "/usr/local/lib/python3.11/smtplib.py", line 716, in login

    raise SMTPNotSupportedError(

smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 486, in thread_handler

    raise exc_info[1]

  File "/takahe/stator/models.py", line 234, in atransition_attempt

    next_state = await current_state.handler(self)  # type: ignore

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/takahe/users/models/password_reset.py", line 27, in handle_new

    await sync_to_async(send_mail)(

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 448, in __call__

    ret = await asyncio.wait_for(future, timeout=None)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 442, in wait_for

    return await fut

           ^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 22, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 490, in thread_handler

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/__init__.py", line 87, in send_mail

    return mail.send()

           ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send

    return self.get_connection(fail_silently).send_messages([self])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 124, in send_messages

    new_conn_created = self.open()

                       ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 91, in open

    self.connection.login(self.username, self.password)

  File "/usr/local/lib/python3.11/smtplib.py", line 716, in login

    raise SMTPNotSupportedError(

smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
```

created the super user with `python3 manage.py createsuperuser` but still I'm pretty sure gmail smtp won't work.
EDIT: Doesn't work. I double checked, all seems fine but python can't get access to gmail smtp.

**Comment by andrewgodwin** [comment]
Port 587 is for TLS connections, so you need to add `?tls=true` to the end, as specified here: https://docs.jointakahe.org/en/latest/installation/#smtp

I know it's not immediately obvious - we should probably detect if someone sets the port and not the TLS flag and warn them!

**Comment by j2l** [comment]
OMG, you're totally right.
I thought I fully read the install page, actually I missed this part. It's working now, thank you @andrewgodwin !
