### ISSUE TITLE
unsupported type <class 'api.schemas.PushSubscriptionCreation'> with latest commit

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#612]
```
takahe_docker-setup-1  | Traceback (most recent call last):
takahe_docker-setup-1  |   File "/takahe/manage.py", line 38, in <module>
takahe_docker-setup-1  |     main()
takahe_docker-setup-1  |   File "/takahe/manage.py", line 34, in main
takahe_docker-setup-1  |     execute_from_command_line(sys.argv)
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
takahe_docker-setup-1  |     utility.execute()
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
takahe_docker-setup-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
takahe_docker-setup-1  |     self.execute(*args, **cmd_options)
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
takahe_docker-setup-1  |     output = self.handle(*args, **options)
takahe_docker-setup-1  |
takahe_docker-setup-1  |  ^^^^^^^^^^^^^^^
takahe_docker-setup-1  | ^^^^^^^^^^^^^
takahe_docker-setup-1  | ^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
takahe_docker-setup-1  |     res = handle_func(*args, **kwargs)
takahe_docker-setup-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 100, in handle
takahe_docker-setup-1  |     self.check(databases=[database])
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
takahe_docker-setup-1  |     all_issues = checks.run_checks(
takahe_docker-setup-1  |                  ^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
takahe_docker-setup-1  |     new_errors = check(app_configs=app_configs, databases=databases)
takahe_docker-setup-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
takahe_docker-setup-1  |     return check_resolver(resolver)
takahe_docker-setup-1  |            ^^^^^^^^^^^^^^^
takahe_docker-setup-1  | ^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
takahe_docker-setup-1  |     return check_method()
takahe_docker-setup-1  |
takahe_docker-setup-1  |    ^^^^^^^^
takahe_docker-setup-1  | ^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
takahe_docker-setup-1  |     for pattern in self.url_patterns:
takahe_docker-setup-1  |                    ^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
takahe_docker-setup-1  |     res = instance.__dict__[self.name] = self.func(instance)
takahe_docker-setup-1  |                                          ^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
takahe_docker-setup-1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
takahe_docker-setup-1  |                        ^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
takahe_docker-setup-1  |     res = instance.__dict__[self.name] = self.func(instance)
takahe_docker-setup-1  |                                          ^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
takahe_docker-setup-1  |     return import_module(self.urlconf_name)
takahe_docker-setup-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
takahe_docker-setup-1  |     return _bootstrap._gcd_import(name[level:], package, level)
takahe_docker-setup-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
takahe_docker-setup-1  |   File "/takahe/takahe/urls.py", line 326, in <module>
takahe_docker-setup-1  |     path("api/", include("api.urls")),
takahe_docker-setup-1  |
takahe_docker-setup-1  |    ^^^^^^^^^^
takahe_docker-setup-1  | ^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
takahe_docker-setup-1  |     urlconf_module = import_module(urlconf_module)
takahe_docker-setup-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
takahe_docker-setup-1  |     return _bootstrap._gcd_import(name[level:], package, level)
takahe_docker-setup-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
takahe_docker-setup-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
takahe_docker-setup-1  |   File "/takahe/api/urls.py", line 4, in <module>
takahe_docker-setup-1  |     from api.views import (
takahe_docker-setup-1  |   File "/takahe/api/views/push.py", line 10, in <module>
takahe_docker-setup-1  |     @api_view.post
takahe_docker-setup-1  |      ^^^^^^^^^^^^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/hatchway/view.py", line 73, in post
takahe_docker-setup-1  |     return cls(view=view, method="post")
takahe_docker-setup-1  |            ^^
takahe_docker-setup-1  | ^^^^^^^^
takahe_docker-setup-1  | ^^^
takahe_docker-setup-1  | ^^^
takahe_docker-setup-1  | ^^
takahe_docker-setup-1  | ^^^^^^^^^
takahe_docker-setup-1  | ^^
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/hatchway/view.py", line 65, in __init__
takahe_docker-setup-1  |     self.compile()
takahe_docker-setup-1  |   File "/usr/local/lib/python3.11/site-packages/hatchway/view.py", line 180, in compile
takahe_docker-setup-1  |     raise ValueError(
takahe_docker-setup-1  | ValueError: Input argument subscription has an unsupported type <class 'api.schemas.PushSubscriptionCreation'>
```

**Comment by andrewgodwin** [comment]
Yeah, the requirements have changed - you need to ensure you have django-hatchway 0.5.2 installed. This was fixed in the requirements file, but maybe you weren't using that?
